OUTPUT_DIR: 'output/'
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "models/R-50.pkl"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_SIZES: (16, 20, 24, 32, 64)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 2000
    POST_NMS_TOP_N_TEST: 2000
    FPN_POST_NMS_TOP_N_TEST: 2000
  ROI_HEADS:
    USE_FPN: True
    DETECTIONS_PER_IMG: 1000
  ROI_BOX_HEAD:
    NUM_CLASSES: 4
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: False
DATASETS:
  TRAIN: ("wami_big_train",)
  TEST: ("wami_big_val",)
INPUT:
  MIN_SIZE_TRAIN: (800,)
  # MIN_SIZE_TRAIN: (1472,1536,1600,1664,1728,1792,)
  #MIN_SIZE_TRAIN: (1920,1984,2048,2112,2176,2240,)
  # MAX_SIZE_TRAIN: 1792
  # MIN_SIZE_TEST: 1600
  # MAX_SIZE_TEST: 1792
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 4
TEST:
  IMS_PER_BATCH: 8